### ISSUE TITLE
Prime Suspect in "Game Breaking" Glitch

### ISSUE THREAD

**Issue by toErIpNid** [bl4ckscor3/ParticleCulling#5]
I've been trying to make a 1.12.2 modpack for me and the buds and I've run into a strange and extensive bug which even affects the game **outside of modded.** Whenever I download this mod, the skybox breaks. Rendering a black flickering streak visible across the sky. The damage is so bad in fact, that it somehow even affects non-modded versions of 1.12.2 (vanilla). I have no idea what's happening here, but it only happens when I download your mod. I have the latest java 8 and nvidia drivers, and it's only repairable with a complete reinstall of minecraft or the mod launcher you're using. 
![2022-01-24_10 47 19](https://user-images.githubusercontent.com/78389307/150878491-4cc96d37-808c-43bb-aefe-f14d0db2aaa1.png)

**Comment by bl4ckscor3** [comment]
Are you using OptiFine?

**Comment by toErIpNid** [comment]
Not at all.

**Comment by bl4ckscor3** [comment]
All right, I've only ever seen this type of error in conjunction with OptiFine, and removing that fixed the issue. Since you said the error persists unless Minecraft or the launcher is reinstalled, I was thinking OptiFine may be present as mod inside the Minecraft jar file itself, making it seem like no mods are installed (since the mods folder is empty).

Particle Culling does not change anything about the sky, it does not change anything else either, other than stopping the call to the code that renders particles. There are no other modifications made that could influence something like this, or things saved that could persist between different Minecraft launches and even into vanilla. 
To try and reproduce this, I installed just Particle Culling v1.3.1 and MixinBootstrap 1.1.0 with Forge 2860, loaded up an instance of Minecraft in a completely empty folder (apart from the mods of course), and I wasn't able to reproduce the issue. It also doesn't make sense that it happens without this mod installed, because how would it be able to change anything if it's not loaded. It's very unlikely to be this mod's fault because of that, and rather an external issue - perhaps something triggered when using different mods (including this one) together that clash, causing some wrong value to be written somewhere that persists over different game launches (but that's a wild theory - I am not aware of something persisting like this). It could be NVIDIA's GPU drivers (I have an AMD GPU, so I can't test that theory).

Unless some clear reproduction steps that work for me can be found, I won't look further into this. I consider this issue out of my control to be fixed.
